
services:
  - type: web
    name: kich-sms-telegram
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    plan: free
    autoDeploy: false
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///instance/telegram_sender.db
    healthCheckPath: /
    disk:
      name: sqlite-data
      mountPath: /app/instance
      sizeGB: 1
